### ISSUE TITLE
Criação das classes de repositório

### ISSUE THREAD

**Issue by rosaigor138** [IF-Trabalhos/SCCO_MVC#6]

**Comment by fsoupimenta** [comment]
@rosaigor138 As classes de repositório já foram criadas, certo?
Acho que já dá pra fechar as issues de criação que a gente já fez, e se tiver algum problema ou mudança no diagrama de classes a gente cria uma nova issue de aprimoramento, pode ser?

**Comment by rosaigor138** [comment]
@fsoupimenta Ainda há a necessidade de verificar se não falta algo, como pesquisas personalizadas que o jpa não disponibiliza. Mas sim podemos fechar algumas delas!
